#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"

mkdir -p "${BASE_DIR}/docs/strategy"
mkdir -p "${BASE_DIR}/docs/governance"
mkdir -p "${BASE_DIR}/docs/development"
mkdir -p "${BASE_DIR}/docs/architecture"
mkdir -p "${BASE_DIR}/docs/security"
mkdir -p "${BASE_DIR}/docs/compliance"
mkdir -p "${BASE_DIR}/docs/operations"
mkdir -p "${BASE_DIR}/docs/training"
mkdir -p "${BASE_DIR}/docs/roadmaps"
mkdir -p "${BASE_DIR}/docs/reports"
mkdir -p "${BASE_DIR}/docs/research"
mkdir -p "${BASE_DIR}/docs/decisions"
mkdir -p "${BASE_DIR}/evidence/approvals"
mkdir -p "${BASE_DIR}/evidence/gates"
mkdir -p "${BASE_DIR}/evidence/validation"
mkdir -p "${BASE_DIR}/evidence/security"
mkdir -p "${BASE_DIR}/evidence/compliance"
mkdir -p "${BASE_DIR}/evidence/performance"
mkdir -p "${BASE_DIR}/evidence/operations"
mkdir -p "${BASE_DIR}/evidence/training"
mkdir -p "${BASE_DIR}/evidence/finance"
mkdir -p "${BASE_DIR}/evidence/state"
mkdir -p "${BASE_DIR}/evidence/state/config_snapshots"
mkdir -p "${BASE_DIR}/evidence/state/checkpoints"
mkdir -p "${BASE_DIR}/evidence/state/audit_logs"
mkdir -p "${BASE_DIR}/state/feature_flags"
mkdir -p "${BASE_DIR}/state/runbooks"
mkdir -p "${BASE_DIR}/state/integration_tests"
mkdir -p "${BASE_DIR}/scripts/tests"
mkdir -p "${BASE_DIR}/scripts/utilities"
mkdir -p "${BASE_DIR}/scripts/migrations"
mkdir -p "${BASE_DIR}/scripts/automation"
mkdir -p "${BASE_DIR}/scripts/analysis"
mkdir -p "${BASE_DIR}/docker/overrides"
mkdir -p "${BASE_DIR}/docker/secrets"
mkdir -p "${BASE_DIR}/docker/config"
mkdir -p "${BASE_DIR}/infrastructure/terraform"
mkdir -p "${BASE_DIR}/infrastructure/ansible"
mkdir -p "${BASE_DIR}/infrastructure/kubernetes"
mkdir -p "${BASE_DIR}/infrastructure/state/locks"
mkdir -p "${BASE_DIR}/infrastructure/state/plans"
mkdir -p "${BASE_DIR}/infrastructure/state/backups"
mkdir -p "${BASE_DIR}/platform/api"
mkdir -p "${BASE_DIR}/platform/web"
mkdir -p "${BASE_DIR}/platform/workers"
mkdir -p "${BASE_DIR}/platform/shared"
mkdir -p "${BASE_DIR}/platform/scripts"
mkdir -p "${BASE_DIR}/tests/unit"
mkdir -p "${BASE_DIR}/tests/integration"
mkdir -p "${BASE_DIR}/tests/system"
mkdir -p "${BASE_DIR}/tests/performance"
mkdir -p "${BASE_DIR}/tests/security"
mkdir -p "${BASE_DIR}/tests/fixtures"
mkdir -p "${BASE_DIR}/config/environments"
mkdir -p "${BASE_DIR}/config/features"
mkdir -p "${BASE_DIR}/config/security"
mkdir -p "${BASE_DIR}/config/compliance"
mkdir -p "${BASE_DIR}/config/monitoring"
mkdir -p "${BASE_DIR}/config/templates"
mkdir -p "${BASE_DIR}/ci/artifacts"
mkdir -p "${BASE_DIR}/ci/logs"
mkdir -p "${BASE_DIR}/ci/reports"
mkdir -p "${BASE_DIR}/ci/config"
mkdir -p "${BASE_DIR}/ci/scripts"
mkdir -p "${BASE_DIR}/packages/python"
mkdir -p "${BASE_DIR}/packages/js"
mkdir -p "${BASE_DIR}/packages/cli"
mkdir -p "${BASE_DIR}/packages/sdks"

echo "Strategic documentation for Phase 0 foundation and beyond." > "${BASE_DIR}/docs/strategy/README.md"
echo "Governance models, branch protection, and RACI matrices." > "${BASE_DIR}/docs/governance/README.md"
echo "Developer onboarding, environment setup, and workflow guides." > "${BASE_DIR}/docs/development/README.md"
echo "Architecture decisions and diagrams supporting roadmap execution." > "${BASE_DIR}/docs/architecture/README.md"
echo "Security policies aligned with ISO 42001 controls." > "${BASE_DIR}/docs/security/README.md"
echo "Compliance guidance covering EU AI Act and GDPR." > "${BASE_DIR}/docs/compliance/README.md"
echo "Operational runbooks and readiness plans for Phase 8." > "${BASE_DIR}/docs/operations/README.md"
echo "Training materials and enablement assets for stakeholders." > "${BASE_DIR}/docs/training/README.md"
echo "Research references and benchmarking data." > "${BASE_DIR}/docs/research/README.md"
echo "Decision logs aligned with UMCA governance." > "${BASE_DIR}/docs/decisions/README.md"
echo "Immutable approval records supporting EU AI Act compliance." > "${BASE_DIR}/evidence/approvals/README.md"
echo "Gate validation outputs for Phase 0 through Phase 8." > "${BASE_DIR}/evidence/gates/README.md"
echo "Machine-readable validation reports for contract enforcement." > "${BASE_DIR}/evidence/validation/README.md"
echo "Security scan outputs preserved for audits." > "${BASE_DIR}/evidence/security/README.md"
echo "Compliance attestations and framework mappings." > "${BASE_DIR}/evidence/compliance/README.md"
echo "Performance benchmarks and service level data." > "${BASE_DIR}/evidence/performance/README.md"
echo "Operational health reports and incident summaries." > "${BASE_DIR}/evidence/operations/README.md"
echo "Training completion evidence and rosters." > "${BASE_DIR}/evidence/training/README.md"
echo "Financial oversight reports and approvals." > "${BASE_DIR}/evidence/finance/README.md"
echo "Configuration snapshots, checkpoints, and audit logs." > "${BASE_DIR}/evidence/state/README.md"
echo "Feature flag states synchronized with deployment cadence." > "${BASE_DIR}/state/feature_flags/README.md"
echo "Integration test orchestration guidance." > "${BASE_DIR}/state/integration_tests/README.md"
echo "Performance benchmarking scenarios and expectations." > "${BASE_DIR}/tests/performance/README.md"
echo "Security test suites aligned with ISO 42001 controls." > "${BASE_DIR}/tests/security/README.md"
echo "CI report archives for traceability and audits." > "${BASE_DIR}/ci/reports/README.md"

touch "${BASE_DIR}/.bootstrap_complete"
echo "Bootstrap complete: canonical directories and README stubs created."
