name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run lint
        run: |
          pip install black==24.8.0
          black --check src
      - name: Run tests
        run: |
          set +e
          if [ -d tests ]; then
            python -m pytest --maxfail=5
            exit_code=$?
            # pytest returns 5 when no tests were collected
            if [ $exit_code -eq 5 ]; then
              echo "No tests collected yet (Phase 0 foundation)"
              exit 0
            fi
            exit $exit_code
          else
            echo "No tests directory present" && exit 0
          fi

  contract-validation:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install validator dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Validate contract
        run: |
          python scripts/validate_contract.py \
            contracts/phase_0_foundation.contract.json \
            --report-path evidence/validation/phase0_contract_validation.json
      - name: Upload validation artifact
        uses: actions/upload-artifact@v4
        with:
          name: phase0-contract-validation
          path: evidence/validation/phase0_contract_validation.json
