name: Security

on:
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches: [main]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: false
          load: true
          tags: ghcr.io/example/phase0:latest
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/example/phase0:latest
          format: cyclonedx-json
          output-file: sbom-phase0.json
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/example/phase0:latest
          severity: HIGH,CRITICAL
          exit-code: '1'
      - name: Upload security report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-report
          path: |
            trivy-report.json
            sbom-phase0.json
